import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav/navbar";

const NotoSansBengali = Noto_Sans_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${NotoSansBengali.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar />

        {children}
      </body>
    </html>
  );
}
